# fly.toml app configuration file generated for jengchiinventoryapi-g7fuiq on 2025-05-04T00:31:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jengchiinventoryapi-g7fuiq'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[vm]
size = "shared-cpu-1x"
memory = 256

